// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'platform_plugin.dart';

// **************************************************************************
// FlutterPluginGenerator
// **************************************************************************

/// **************************************************************************
/// This code is autogenerated for you by the flutter_plugin_generator package.
///
/// For all inquiry, please read the documentation or file an issue:
/// Project Github : https://github.com/BugsBunnyBR/plugin_gen.flutter/
///
/// Annotations :https://github.com/BugsBunnyBR/plugin_gen.flutter/tree/master/flutter_plugin_annotations
/// Generator : https://github.com/BugsBunnyBR/plugin_gen.flutter/tree/master/flutter_plugin_generator
///
/// This file can be recreated running the command below in the plugin directory.
/// ```
///  flutter pub run build_runner build --delete-conflicting-outputs
/// ```
/// **************************************************************************

class _$PlatformPlugin extends PlatformPlugin {
  final MethodChannel _methodChannel = const MethodChannel('platform_plugin');

  _$PlatformPlugin() : super();

  @override
  Future<String> get platformVersion async {
    final result = await _methodChannel.invokeMethod<String>('platformVersion');

    return result;
  }
}
